name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on:
  pull_request:
    branches:
      - master
      - develop


jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  quality-code:
    # Name the Job
    name: Check quality and style of python code
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.3.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}